### PR TITLE
attr,build: add TOPFRAME attribute

### PR DESCRIPTION
**Pull request by zchee**
Add `TOPFRAME` attribute.
Go runtime has been added `TOPFRAME` attribute, kept in sync.

### CODE REVIEW

**Comment by zchee** [comment]
@mmcloughlin BTW, https://golang.org/cl/155927 CL has been merged. I think would be better to add `REFLECTMETHOD` to `attrname` map.

https://github.com/mmcloughlin/avo/blob/c8004ba627cacd7bab12cf9243c2f14d89c71cbe/attr/attr.go#L96

**Comment by zchee** [comment]
ah, CI was failed :(
Should I also update `tests/textflag/zattrtest.s` file?

**Comment by mmcloughlin** [comment]
@zchee thank you for the PR!

Yes, you are right about `REFLECTMETHOD`. If you could add it to that map and remove the comment that would be great. I think you'll also need to update a test.

I think the CI build failed because you did not rerun code generation. You should just need to run `./script/generate` to update the `tests/textflag/zattrtest.s` file.

**Comment by zchee** [comment]
@mmcloughlin 
will doing ~12h. now 6 AM in Japan :P

**Comment by zchee** [comment]
@mmcloughlin sorry for late. included `REFLECTMETHOD` and re-generate `tests/textflag/zattrtest.s`.
PTAL.

**Comment by mmcloughlin** [comment]
Thank you for your contribution!

**Pull request merged**
