### PR TITLE
all: add GFNI instructions

### PR DESCRIPTION
**Pull request by mmcloughlin**
Based on #343

Updates #335

### CODE REVIEW

**Comment by mmcloughlin** [comment]
@klauspost It appears the opcodes without `V` prefix are not recognized by Go assembler:

```
--- FAIL: TestAssembles (1.24s)
    load_test.go:30: exec: [/opt/hostedtoolcache/go/1.18.8/x64/bin/go tool asm -e -o /tmp/avo2003297476/asm.o /tmp/avo2003297476/asm.s]
    load_test.go:30: output:
        /tmp/avo200329[74](https://github.com/mmcloughlin/avo/actions/runs/3559848371/jobs/5979483745#step:8:75)76/asm.s:841: unrecognized instruction "GF2P8AFFINEINVQB"
        /tmp/avo2003297476/asm.s:842: unrecognized instruction "GF2P8AFFINEINVQB"
        /tmp/avo20032974[76](https://github.com/mmcloughlin/avo/actions/runs/3559848371/jobs/5979483745#step:8:77)/asm.s:845: unrecognized instruction "GF2P8AFFINEQB"
        /tmp/avo2003297476/asm.s:846: unrecognized instruction "GF2P8AFFINEQB"
        /tmp/avo2003297476/asm.s:849: unrecognized instruction "GF2P8MULB"
        /tmp/avo2003297476/asm.s:850: unrecognized instruction "GF2P8MULB"
        asm: assembly of /tmp/avo2003297476/asm.s failed
```

**Comment by klauspost** [comment]
@mmcloughlin Thanks a bunch. Added it to https://github.com/klauspost/reedsolomon/pull/228 - going in after a bit of testing.

Sorry about the extra work. I will try to catch up on what you did so I can give you a more finished update if I should need it in the future.

**Comment by mmcloughlin** [comment]
> @mmcloughlin Thanks a bunch. Added it to [klauspost/reedsolomon#228](https://github.com/klauspost/reedsolomon/pull/228) - going in after a bit of testing.
> 
> Sorry about the extra work. I will try to catch up on what you did so I can give you a more finished update if I should need it in the future.

Yeah no worries at all! This was always something I needed to work on, and GFNI turned out to be a nice small example to get things going. Having done this I can return to #234 and finally land it.

Great to see it in https://github.com/klauspost/reedsolomon/pull/228 so quickly.

**Comment by vsivsi** [comment]
@mmcloughlin See newly updated PRs #234 and #349. Both caught-up with latest `master` and adopting the `opcodesextra` mechanism for adding new instructions. Those two PRs plus this one should bring Avo up to all AVX512 features currently supported by the Go assembler.

**Pull request merged**
