### PR TITLE
Support AVX512_BITALG instructions and relax base register req in VM operands

### PR DESCRIPTION
**Pull request by vsivsi**
This PR updates the AVX512 branch only, and brings the following:

* Relaxes the current requirement that VM operands in VPSCATTER/GATHER have a base register.
    * This is not required by AVX512 or the golang assembler, as discussed here: https://github.com/mmcloughlin/avo/issues/193

* Adds support for [AVX512_BITALG](https://en.wikipedia.org/wiki/AVX-512#VPOPCNTDQ_and_BITALG) instructions / forms.
    * Adds VPOPCNTB/W byte/word forms of VPOPCNT, including AVX512VL 128/256-bit wide (xmm/ymm) forms
    * Adds AVX512VL 128/256-bit wide (xmm/ymm) forms to the existing supported AVX512_VPOPCNTDQ instructions.
    * Adds new instruction VPSHUFBITQMB with its AVX512VL 128/256-bit wide (xmm/ymm) forms.
    * Support for these instructions/forms was hand edited into `internal/data/x86_64.xml` as that seemed the path of least resistance, and `scripts/generate` was run to regenerate `build/zinstructions.go` et al. 

Additionally it:
* Merges in all changes from the current `master` branch
* Updates CI for go1.17 (from `go1.17` branch)

### CODE REVIEW

**Comment by vsivsi** [comment]
I'm not sure why the `lint` CI run is exiting with retval 1. But it looks like lint has been failing for the AVX512 branch all along.

It also looks like link and thirdparty are currently failing on the go1.17 branch, and since I merged that in... Also failing here.

Perhaps it was a mistake to do that, happy to revert the CI to 1.16 on this branch if moving to 1.17 is complicated.

**Comment by vsivsi** [comment]
@mmcloughlin  What needs to happen to get this merged?  This is the last thing blocking me from moving off my fork and back to Avo `master`.  Specifically this addresses #193 and #199. If it would be helpful to have me resubmit this as a PR against the master branch, I'd be happy to do that.

**Comment by mmcloughlin** [comment]
Can we split this into two?

For the BITALG stuff, I'd like any hand edits to be recorded as patch files. It's looking unlikely that opcodes will ever be updated, but in theory, it could be. Basically, we need to get to the point where running the `dl.sh` script produces the datafiles. I'd suggest a PR that:

* adds a `internal/data/patches/avx512bitalg.patch`
* update `internal/data/dl.sh` script to add an `applypatch` function
* the `applypatch` function should call the `patch` command with a given patch file
* `echo` some output to record the patch in the `internal/data/README.md` file

For the vm operands, it basically looks good but it needs more tests. Let me take a look at this.

**Comment by vsivsi** [comment]
Sure thing! Thanks for the quick response. Here's a new PR for the S/G mem op validation: https://github.com/mmcloughlin/avo/pull/233

**Comment by vsivsi** [comment]
And another PR with the requested patch file. https://github.com/mmcloughlin/avo/pull/234

If it's not too much to ask, I'll leave the patching mechanics and opcodes rebuild up to you, since you seem to have a vision for how that should all work that would probably take longer to communicate than to just implement.

**Comment by vsivsi** [comment]
With #233 and #234 this PR is now defunct, so I'm closing it.

**Comment by mmcloughlin** [comment]
> If it's not too much to ask, I'll leave the patching mechanics and opcodes rebuild up to you, since you seem to have a vision for how that should all work that would probably take longer to communicate than to just implement.

For sure.

**Pull request closed without merging**
